# Run as 
# ansible-playbook --ask-become-pass -i "localhost," osx-dev-setup.yml
---
- name: Personal development setup for OSX
  hosts: localhost 
  connection: local 
  tasks:
  
  - name: Testing sudo password
    become: True
    shell: echo "It works!"

  - name: Install cask applications 
    homebrew_cask:
      name:  "{{ item }}"
    with_items:
    - cyberduck
    - docker
    - google-chrome
    - google-cloud-sdk
    - google-backup-and-sync
    - intellij-idea-ce
    - iterm2
    - java
    - postgres
    - psequel
    - pgadmin4
    - slack
    - skype
    - typora
    - visual-studio-code
    - virtualbox
    - vagrant

  - name: Install brew applications 
    homebrew:
      name:  "{{ item }}"
      state: present
    with_items:
    - bfg
    - docker-cloud
    - htop
    - pgcli
    - python3
    - telnet
    - wget
    - inetutils
    - git-flow-avh
    - https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb

  - name: Install sshpass
    command: brew install https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb

  - name: Install pip applications 
    become: true
    pip:
      name: "{{ item }}"
      extra_args: --user
    with_items:
    - docker-cloud
    - pgcli
    - virtualenv
    - virtualenvwrapper
    - awscli

  - name: Increase sudo timeout
    become: true
    lineinfile:
      create: true
      path: /private/etc/sudoers.d/timeout
      validate: 'visudo -cf %s'
      line: Defaults timestamp_timeout=60

